apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kvdi.fullname" . }}-manager
  labels:
    {{- include "kvdi.labels" . | nindent 4 }}
rules:

- apiGroups:
  - ""
  resources:
    - namespaces
  verbs:
    - watch
    - get
    - list

- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - clusterroles
  verbs:
  - create
  - update
  - delete
  - get
  - list
  - patch
  - update
  - watch

- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  - services
  - services/finalizers
  - serviceaccounts
  - endpoints
  - persistentvolumeclaims
  - persistentvolumes
  - configmaps
  - secrets
  verbs:
  - '*'

- apiGroups:
  - apps
  resources:
  - deployments
  - replicasets
  verbs:
  - '*'

- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  - prometheuses
  verbs:
  - get
  - create
  - update
  - list
  - watch

- apiGroups:
  - kvdi.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - cert-manager.io
  resources:
  - certificates
  - issuers
  - clusterissuers
  verbs:
  - create
  - update
  - delete
  - list
  - get
  - watch

{{- if .Values.rbac.pspEnabled }}
- apiGroups:
  - policy
  verbs:
  - use
  resources:
  - podsecuritypolicies
  resourceNames:
  - {{ include "kvdi.fullname" . }}-psp
{{- end }}
